### ISSUE TITLE
Slack DM for mentions

### ISSUE THREAD

**Issue by LeanderK** [Rafase282/SlackNPodio#11]
i don't know how feasible this would be, but a DM when somebody mentions you on podio would be nice.

Use-Case: Another team i work with uses podio to manage their stuff, but we do not use it internally. So i don't always notice when i get mentioned, wich is not ideal. I have emails enabled, but i get a lot of noise there, so suboptimal.

**Comment by LeanderK** [comment]
bot.js looks surprisingly simpel 😄 if it's doable and the feature is wished might create a pull-request.

**Comment by Rafase282** [comment]
That seems useful. We are currently planing for the features that we want to implement.

If you can implement that then feel free to submit a PR.

**Comment by LeanderK** [comment]
i can look into and try managing it on my own, but i am busy until at least next friday, depending on some other things i may not have time until the end of april.

**Comment by Rafase282** [comment]
We will see then, were you on the meeting today? If anything @flyblackbox can note the suggestion and put it on the report he is preparing.

If you already have an idea of how it can be implemented via the podio api let me know and I can look into it this weekend or monday.

**Comment by Rafase282** [comment]
@LeanderK I have made some changes recently that might looks like things are more complicated but now there is a method to everything.

**Comment by flyblackbox** [comment]
@LeanderK are you still interested in this feature? Would love some help to implement your vision if you have the time now.

**Comment by LeanderK** [comment]
We decided to move away from podio, so I am afraid there's not motivation on my part to implement the ticket 😕

**Comment by flyblackbox** [comment]
Oh interesting! Do you mind if I ask what platform you've migrated to that is replacing Podio now?

**Comment by LeanderK** [comment]
We had repeated complains about podio being hard to use, slow etc. which hindered adoption. We don't use all features of podio and are currently evaluating a few competitiors, https://www.teamwave.com looks the most promising feature-wise.
